- name: Launch app
  docker_container:
      name: simple-api
      image: mdebbah/tp-devops-simple-api:latest
      networks:
          - name: tp-network
      env:
          DATABASE_HOST: database
          DATABASE_PASSWORD: pwd
