- name: Launch proxy
  docker_container:
      name: proxy
      image: mdebbah/tp-devops-http-server:latest
      pull: always
      restart: true
      networks:
          - name: tp-network-app
      ports:
          - "80:80"
