name: Deploy
on:
    workflow_run:
        workflows: ["Publish"]
        types: [completed]
        branches: ["main"]

jobs:
    deploy-with-ansible:
        runs-on: ubuntu-24.04
        steps:
            - name: Copy SSH key
              run: echo ${{ secret.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa_devops

            - name: Run playbook
              uses: dawidd6/action-ansible-playbook@v4
              with:
                  playbook: playbook.yaml
                  directory: ./ansible/
                  options: --inventory inventories/setup.yaml
