name: Deploy
on:
    workflow_run:
        workflows: ["Publish"]
        types: [completed]
        branches: ["main"]

jobs:
    deploy-with-ansible:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run playbook
              uses: dawidd6/action-ansible-playbook@v4
              with:
                  playbook: playbook.yaml
                  directory: ./ansible/
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  options: --inventory inventories/setup.yaml
