name: Git
on:
    push:
        branches-ignore: ["main"]

jobs:
    create-pr:
        runs-on: ubuntu-24.04
        steps:
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7
              with:
                  committer: debbahmartin@gmail.com
                  author: debbahmartin@gmail.com
                  
