name: CI devops 2025
on:
    push:
        branches:
            - main
            - develop
    pull_request:

jobs:
    test-backend:
        runs-on: ubuntu-24.04
        steps:
            #checkout your github code using actions/checkout@v4
            - name: Checkout
              uses: actions/checkout@v4

            #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "21"

            #finally build your app with the latest command
            - name: Build and test with Maven
              run: mvn verify --file simple-api/pom.xml

    build-and-push-docker-image:
        needs: test-backend
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            - name: Build image and push backend
              uses: docker/build-push-action@v6
              with:
                  context: ./simple-api
                  tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-simple-api:latest
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Build image and push database
              uses: docker/build-push-action@v6
              with:
                  context: ./database
                  tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-database:latest
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Build image and push httpd
              uses: docker/build-push-action@v6
              with:
                  context: ./http-server
                  tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-http-server:latest
                  push: ${{ github.ref == 'refs/heads/main' }}
