name: Publish
on:
    workflow_run:
        workflows: ["Test"]
        types: [completed]
        branches: ["main"]

jobs:
    build-and-push-docker-image:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            - name: Build image and push backend
              uses: docker/build-push-action@v6
              with:
                  context: ./simple-api
                  tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-simple-api:latest
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Build image and push frontend
              uses: docker/build-push-action@v6
              with:
                  context: ./front
                  tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-front:latest
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Build image and push database
              uses: docker/build-push-action@v6
              with:
                  context: ./database
                  tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-database:latest
                  push: ${{ github.ref == 'refs/heads/main' }}

            - name: Build image and push httpd
              uses: docker/build-push-action@v6
              with:
                  context: ./http-server
                  tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-http-server:latest
                  push: ${{ github.ref == 'refs/heads/main' }}
